DROP RULE IF EXISTS create_auction ON auction;
DROP RULE IF EXISTS update_auction ON auction;
DROP RULE IF EXISTS delete_auction ON auction;

DROP TABLE IF EXISTS products, auction, auction_logs;

DROP TYPE IF EXISTS actions;

CREATE TYPE actions AS ENUM ('create', 'update', 'delete');

CREATE TABLE products
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auction
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER REFERENCES products (id),
    ts      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    item    VARCHAR(50)    NOT NULL,
    bid     DECIMAL(10, 2) NOT NULL
);

CREATE TABLE auction_logs
(
    action actions,
    id     INTEGER,
    ts     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    item   VARCHAR(50)    NOT NULL,
    bid    DECIMAL(10, 2) NOT NULL
);

CREATE OR REPLACE FUNCTION upd_timestamp() RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    NEW.ts = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER auto_timestamp
  BEFORE UPDATE
  ON auction
  FOR EACH ROW
  EXECUTE PROCEDURE upd_timestamp();


CREATE INDEX id_auction ON auction_logs (id);

CREATE RULE create_auction AS ON INSERT TO auction DO
    INSERT INTO auction_logs (action, id, ts, item, bid)
    VALUES ('create', (SELECT currval('auction_id_seq')), current_timestamp, NEW.item, NEW.bid);

CREATE RULE update_auction AS ON UPDATE TO auction DO
    INSERT INTO auction_logs (action, id, ts, item, bid)
    VALUES ('update', OLD.id, current_timestamp, NEW.item, NEW.bid);

CREATE RULE delete_auction AS ON DELETE TO auction DO
    INSERT INTO auction_logs (action, id, ts, item, bid)
    VALUES ('delete', OLD.id, current_timestamp, OLD.item, OLD.bid);

INSERT INTO products (name)
VALUES ('Sega'),
       ('Nintendo'),
       ('Sony');

INSERT INTO auction (item, item_id, bid)
VALUES ('Sega', 1, 105.2356),
       ('Nintendo', 2, 1658.456),
       ('Sony', 3, 1658.456);

UPDATE auction
SET bid = 108.845
WHERE item_id = 1;

UPDATE auction
SET bid = 109.845
WHERE item_id = 1;

UPDATE auction
SET bid = 110.86
WHERE item_id = 3;

UPDATE auction
SET bid = 1108.999
WHERE item_id = 3;

UPDATE auction
SET bid = 1201.35
WHERE item_id = 3;
